export { default as bgPatternCircles } from "./images/bg-pattern-circles.svg"
export { default as bgPatternIntroDesktop } from "./images/bg-pattern-intro-desktop.svg"
export { default as bgPatternIntroMobile } from "./images/bg-pattern-intro-mobile.svg"
export { default as iconArrowDark } from "./images/icon-arrow-dark.svg"
export { default as iconArrowLight } from "./images/icon-arrow-light.svg"
export { default as iconClose } from "./images/icon-close.svg"
export { default as iconHamburger } from "./images/icon-hamburger.svg"
export { default as illustrationEditorDesktop } from "./images/illustration-editor-desktop.svg"
export { default as illustrationEditorMobile } from "./images/illustration-editor-mobile.svg"
export { default as illustrationLaptopDesktop } from "./images/illustration-laptop-desktop.svg"
export { default as illustrationLaptopMobile } from "./images/illustration-laptop-mobile.svg"
export { default as illustrationPhones } from "./images/illustration-phones.svg"
export { default as logo } from "./images/logo.svg"

