export { default as bgPatternFooterDesktop } from "./images/bg-pattern-footer-desktop.svg"
export { default as bgPatternFooterMobile } from "./images/bg-pattern-footer-mobile.svg"
export { default as bgPatternHowWeWorkDesktop } from "./images/bg-pattern-how-we-work-desktop.svg"
export { default as bgPatternHowWeWorkMobile } from "./images/bg-pattern-how-we-work-mobile.svg"
export { default as bgPatternIntroLeftDesktop } from "./images/bg-pattern-intro-left-desktop.svg"
export { default as bgPatternIntroLeftMobile } from "./images/bg-pattern-intro-left-mobile.svg"
export { default as bgPatternIntroRightDesktop } from "./images/bg-pattern-intro-right-desktop.svg"
export { default as bgPatternIntroRightMobile } from "./images/bg-pattern-intro-right-mobile.svg"
export { default as bgPatternMobileNav } from "./images/bg-pattern-mobile-nav.svg"
export { default as bgPatternTabletNav } from "./images/bg-pattern-tablet-nav.svg"
export { default as iconAffordablePrices } from "./images/icon-affordable-prices.svg"
export { default as iconClose } from "./images/icon-close.svg"
export { default as iconFacebook } from "./images/icon-facebook.svg"
export { default as iconHamburguer } from "./images/icon-hamburger.svg"
export { default as iconInstagram } from "./images/icon-instagram.svg"
export { default as iconPeopleFirst } from "./images/icon-people-first.svg"
export { default as iconPinterest } from "./images/icon-pinterest.svg"
export { default as iconSnappyProcess } from "./images/icon-snappy-process.svg"
export { default as iconTwitter } from "./images/icon-twitter.svg"
export { default as iconIntroDesktop } from "./images/image-intro-desktop.jpg"
export { default as iconIntroMobile } from "./images/image-intro-mobile.jpg"
export { default as logo } from "./images/logo.svg"

export { default as imgIntroDesktop } from "./images/image-intro-desktop.jpg"
export { default as imgIntroMobile } from "./images/image-intro-mobile.jpg"

