import localFont from "next/font/local"
import { SidebarDemo } from "./components/layout/Sidebar/SidebarDemo"
import "./globals.css"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
})
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <main className="max-w-screen min-h-screen overflow-x-hidden">

          <SidebarDemo >

            {children}
          </SidebarDemo>
        </main>
      </body>
    </html>
  )
}
