export { default as iconMenuClose } from "./images/icon-menu-close.svg"
export { default as iconMenu } from "./images/icon-menu.svg"
export { default as imageGamingGrowth } from "./images/image-gaming-growth.jpg"
export { default as imageRetroPcs } from "./images/image-retro-pcs.jpg"
export { default as imageTopLaptops } from "./images/image-top-laptops.jpg"
export { default as imageWeb3Desktop } from "./images/image-web-3-desktop.jpg"
export { default as imageWeb3Mobile } from "./images/image-web-3-mobile.jpg"
export { default as logo } from "./images/logo.svg"
